# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

# Backend plugin registrants for non-default log backends (file, remote, slog).
# Each registrant is an additive Bazel dep that registers its creator function
# into the global backend table during static initialization.

load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")
load("@score_baselibs//:bazel/unit_tests.bzl", "cc_unit_test_suites_for_host_and_qnx")

COMPILER_WARNING_FEATURES = [
    "treat_warnings_as_errors",
    "additional_warnings",
    "strict_warnings",
]

# Plugin: DLT File Logging
# Add this dep to your binary to enable file-based DLT logging.
cc_library(
    name = "file",
    srcs = select({
        "//score/mw/log/detail/flags:config_KFile_Logging": ["file_registrant.cpp"],
        "//conditions:default": [],
    }),
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = ["//visibility:public"],  # platform_only
    deps = [
        "@score_baselibs//score/mw/log:minimal",
    ] + select({
        "//score/mw/log/detail/flags:config_KFile_Logging": [
            "//score/mw/log/detail/file_recorder:file_recorder_factory",
        ],
        "//conditions:default": [],
    }),
    alwayslink = True,
)

# Plugin: Remote DLT logging.
# By default the DLTv1 support is used. With --@score_logging//score/mw/log/flags:shm_dma_enabled=True,
# the remote backend uses the DLTv2 backend that uses the Generic Trace Library (GTL) implementation.
cc_library(
    name = "remote",
    srcs = select({
        "//score/mw/log/flags:Remote_Logging": ["remote_registrant.cpp"],
        "//score/mw/log/flags:config_use_shm_dma_enabled": [],
        "//conditions:default": [],
    }),
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = ["//visibility:public"],  # platform_only
    deps = [
        "@score_baselibs//score/mw/log:minimal",
    ] + select({
        "//score/mw/log/flags:Remote_Logging": [
            "//score/mw/log/detail/data_router:remote_dlt_recorder_factory",
        ],
        "//score/mw/log/flags:config_use_shm_dma_enabled": [
            "//score/mw/log/detail/dlt_trace:dlt_trace_registrant",
            # Temporary solution for fixing leaking transitively through @score_logging//score/mw/log, which only happens for
            # certain values of --@score_logging//score/mw/log/flags:shm_dma_enabled.
            "//score/mw/log/legacy_non_verbose_api",
            "@score_baselibs//score/concurrency",
            "@score_baselibs//score/os:errno_logging",
            "@score_communication//score/memory/shared",
        ],
        "//conditions:default": [],
    }),
    alwayslink = True,
)

# Plugin: QNX slog2 System Logging
# Automatically included on QNX builds.
cc_library(
    name = "slog",
    srcs = ["slog_registrant.cpp"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    target_compatible_with = ["@platforms//os:qnx"],
    visibility = ["//visibility:public"],  # platform_only
    deps = [
        "//score/mw/log/detail/slog:slog_recorder_factory",
        "@score_baselibs//score/mw/log:minimal",
    ],
    alwayslink = True,
)

# Plugin: Linux syslog(3) System Logging
# Automatically included on Linux (HGY aarch64 / x86 host) builds.
cc_library(
    name = "syslog",
    srcs = ["syslog_registrant.cpp"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    target_compatible_with = ["@platforms//os:linux"],
    visibility = ["//visibility:public"],  # platform_only
    deps = [
        "//score/mw/log/detail/syslog:syslog_recorder_factory",
        "@score_baselibs//score/mw/log:minimal",
    ],
    alwayslink = True,
)

# Plugin: Custom user-provided Logging backend
# Opt-in. Build with --@score_logging//score/mw/log/flags:KCustom_Logging=True
# and --@score_logging//score/mw/log/flags:custom_recorder_impl=//your:target.
cc_library(
    name = "custom",
    srcs = select({
        "//score/mw/log/flags:Custom_Logging": ["custom_registrant.cpp"],
        "//conditions:default": [],
    }),
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = ["//visibility:public"],
    deps = [
        "@score_baselibs//score/mw/log:minimal",
    ] + select({
        "//score/mw/log/flags:Custom_Logging": [
            "//score/mw/log/flags:custom_recorder_impl",
        ],
        "//conditions:default": [],
    }),
    alwayslink = True,
)

cc_test(
    name = "file_registrant_test",
    srcs = select({
        "//score/mw/log/detail/flags:config_KFile_Logging": ["file_registrant_enabled_test.cpp"],
        "//conditions:default": ["file_registrant_disabled_test.cpp"],
    }),
    features = COMPILER_WARNING_FEATURES + [
        "aborts_upon_exception",
    ],
    tags = ["unit"],
    deps = [
        ":file",
        "@googletest//:gtest_main",
        "@score_baselibs//score/mw/log",
    ],
)

cc_test(
    name = "remote_registrant_test",
    srcs = select({
        "//score/mw/log/flags:Remote_Logging": ["remote_registrant_enabled_test.cpp"],
        "//conditions:default": ["remote_registrant_disabled_test.cpp"],
    }),
    features = COMPILER_WARNING_FEATURES + [
        "aborts_upon_exception",
    ],
    tags = ["unit"],
    deps = [
        ":remote",
        "@googletest//:gtest_main",
        "@score_baselibs//score/mw/log",
    ],
)

cc_test(
    name = "slog_registrant_test",
    srcs = ["slog_registrant_test.cpp"],
    features = COMPILER_WARNING_FEATURES + [
        "aborts_upon_exception",
    ],
    tags = ["unit"],
    target_compatible_with = ["@platforms//os:qnx"],
    deps = [
        ":slog",
        "@googletest//:gtest_main",
        "@score_baselibs//score/mw/log",
    ],
)

cc_unit_test_suites_for_host_and_qnx(
    name = "unit_tests",
    cc_unit_tests = [
        ":file_registrant_test",
        ":remote_registrant_test",
        ":slog_registrant_test",
    ],
    visibility = [
        "@score_baselibs//score/mw/log:__pkg__",
    ],
)
