# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Test and Build Docs

permissions:
  contents: write
  pages: write
  pull-requests: write
  id-token: write

on:
  pull_request_target:
    types: [opened, reopened, synchronize] # Allows forks to trigger the docs build
  push:
    branches:
      - main
  merge_group:
    types: [checks_requested]

jobs:
  docs-verify:
    uses: eclipse-score/cicd-workflows/.github/workflows/docs-verify.yml@c1c90b1a82a1fab0fc202979dde6686b2162d5a8 # v0.0.0
    permissions:
      pull-requests: write
      contents: read
    with:
      bazel-docs-verify-target: "--lockfile_mode=error //:docs_check"

  run-tests:
    uses: ./.github/workflows/coverage_report.yml
    permissions:
      contents: read
      pull-requests: read

  build-docs:
    needs: [run-tests, docs-verify]
    if: ${{ needs.run-tests.result == 'success' }}
    uses: eclipse-score/cicd-workflows/.github/workflows/docs.yml@c1c90b1a82a1fab0fc202979dde6686b2162d5a8 # v0.0.0
    permissions:
      contents: write
      pages: write
      pull-requests: write
      id-token: write
    with:
      # the bazel-target depends on your repo specific docs_targets configuration (e.g. "suffix")
      bazel-target: "--lockfile_mode=error //:docs -- --github_user=${{ github.repository_owner }} --github_repo=${{ github.event.repository.name }}"
      retention-days: 3
      tests-report-artifact: logging_cpp_coverage
